### ISSUE TITLE
Accented letters not transcribed properly

### ISSUE THREAD

**Issue by TheNew000** [flozz/stone.js#10]
Currently attempting to pass any string with an accented letter is causing the translated string to render with unwanted characters.  Here is some simple code to replicate the issue.  

```
<html>
<head>
    <script src="stonejs.min.js"></script>
    <script>
         let catalogs = {
	     "fr": {
		      "plural-forms": "nplurals=2; plural=(n > 1);",
		      "messages": {
			      "Privacy": ["Confidentialité"]
		      }
	     },
        }
        Stone.addCatalogs(catalogs);  
        Stone.enableDomScan(true);  
    </script>
</head>
<body onLoad="Stone.setLocale('fr')">
    <div stonejs>Privacy</div>
</body>
</html>
```

Currently, this string is being rendered as: ' ConfidentialitÃ©' after the translation.

**Comment by flozz** [comment]
I close this issue as it is old... sorry for the lack of response.
