### ISSUE TITLE
Add support for context

### ISSUE THREAD

**Issue by Krenodeno** [flozz/stone.js#32]
As stated in the original PO doc: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

We can have a `msgctxt` line wich tell the translator the context of the string to be translated. Example:
"Back", in English, can be translated as "Arrière" and "Retour" in French, and there is no way to tell the translator the one we want to use (or hacky ways).

It could be provided with a `context` member inside the optional second parameter of Gettext and its variants. Any advice on that ?

Then it would need flozz/sonejs-tools to be updated too.

**Comment by Krenodeno** [comment]
Okay, it will need to implement different functions like in python: https://docs.python.org/fr/3/library/gettext.html#gettext.pgettext

**Comment by flozz** [comment]
It is on `master` and will be released in few minutes :)
