### ISSUE TITLE
Possibility to support JSX format

### ISSUE THREAD

**Issue by baptistedonaux** [flozz/stone.js#8]
The JSX format seems unsupported. It's easy to implement it ?

```
$ stonejs extract "./app/Resources/public/js/**/*.js?(x)" /tmp/catalog.pot
  * Extracting strings from './app/Resources/public/js/main.jsx'
WARN: SyntaxError: Unexpected token <
WARN: File skipped due to syntax errors
```

**Comment by flozz** [comment]
This issue concerns stonejs-tools and seems to be related to this issue: flozz/stonejs-tools#4. I close this issue, please subscribe to the stonejs-tools' one to stay notified of its resolution.
